language: node_js

node_js:
  - "8"
  - "7"
  - "6"
  - "4"


script:
  - npm run coveralls

after_script:
  - ./tools/website.sh

notifications:
  email:
    on_success: never
    on_failure: always
